default:
  navigation:
    - title: Men
      subtitle: Categories
      url: /men
      items:
        - :title: Casual
          :url: /t/men/casual
        - :title: Street
          :url: /t/men/street
        - :title: Active
          :url: /t/men/active
        - :title: Kicks
          :url: /t/men/kicks
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Women
      subtitle: Categories
      url: /women
      items:
        - :title: Active
          :url: /t/women/active
        - :title: Artsy
          :url: /t/women/artsy
        - :title: Chic
          :url: /t/women/chic
        - :title: Bohemian
          :url: /t/women/bohemian
        - :title: Casual
          :url: /t/women/casual
        - :title: Sexy
          :url: /t/women/sexy
        - :title: Kicks
          :url: /t/women/kicks
        - :title: Street
          :url: /t/women/street
        - :title: Curve
          :url: /t/women/curve
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
